import { NextRequest, NextResponse } from "next/server";
import { createAgentDynamicVariables } from "@/lib/agent-context";
import * as publicSiteService from "@/lib/services/publicSite";
import { getGeminiCredentials } from "@/lib/services/settings";

export const runtime = "nodejs";

async function callGeminiApi(apiKey: string, model: string, contents: any[], systemInstruction: string) {
  const primaryUrl = `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(apiKey)}`;
  
  const payload = {
    contents,
    systemInstruction: {
      parts: [{ text: systemInstruction }],
    },
    generationConfig: {
      temperature: 0.7,
      maxOutputTokens: 800,
    },
  };

  let res = await fetch(primaryUrl, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });

  // Fallback to gemini-2.0-flash or gemini-1.5-flash if model name is unrecognized
  if (!res.ok && model.includes("2.5")) {
    const fallbackUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${encodeURIComponent(apiKey)}`;
    res = await fetch(fallbackUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
  }

  if (!res.ok) {
    const errorData = await res.json().catch(() => null);
    throw new Error(errorData?.error?.message || `Gemini API request failed with status ${res.status}`);
  }

  const data = await res.json();
  const replyText = data?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!replyText) {
    throw new Error("No response generated by Gemini AI.");
  }

  return replyText;
}

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ siteSlug: string }> },
) {
  const { siteSlug } = await params;
  try {
    const body = await request.json().catch(() => ({}));
    const { message, history } = body;

    if (!message || typeof message !== "string") {
      return NextResponse.json({ error: "Message is required." }, { status: 400 });
    }

    const { apiKey, model } = await getGeminiCredentials();

    const published = await publicSiteService.getPublishedBySlug(siteSlug);
    if (!published) {
      return NextResponse.json({ error: "Public site not found." }, { status: 404 });
    }

    const dynamicVars = createAgentDynamicVariables({
      siteSlug: published.site.siteSlug,
      businessName:
        (published.site as any).config?.businessName ||
        (published.site as any).businessName ||
        published.organization.name,
      description:
        (published.site as any).config?.about ||
        (published.site as any).about ||
        "",
      timezone: published.organization.timezone,
      locale: published.organization.locale,
      currency: published.organization.currency,
      terminology: published.organization.terminology,
      offerings: published.offerings,
      teamMembers: published.teamMembers,
      knowledgeItems: published.knowledgeItems,
    });

    const systemInstruction = `You are the front-desk AI Receptionist for ${dynamicVars.business_name}.
Your job is to answer questions, guide visitors, check availability, and help book appointments warmly and concisely as a real human receptionist would.

BUSINESS DETAILS & KNOWLEDGE BASE:
${dynamicVars.system_instruction_context}

RULES:
1. Always introduce yourself as the front-desk AI receptionist for ${dynamicVars.business_name}.
2. Keep responses natural, warm, conversational, and concise (1-3 sentences max).
3. Do not invent fake availability; use provided offerings and business hours.
4. Speak naturally in standard, humanlike conversational English.`;

    const contents: any[] = [];
    if (Array.isArray(history)) {
      for (const h of history) {
        if (h.role && h.content) {
          contents.push({
            role: h.role === "user" ? "user" : "model",
            parts: [{ text: h.content }],
          });
        }
      }
    }

    contents.push({
      role: "user",
      parts: [{ text: message }],
    });

    const reply = await callGeminiApi(apiKey, model, contents, systemInstruction);

    return NextResponse.json({
      success: true,
      provider: "gemini",
      model,
      reply,
    });
  } catch (error) {
    console.error("Gemini chat route error", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Gemini receptionist session error." },
      { status: 500 },
    );
  }
}
